---
- name: Create config folder
  command: mkdir ~/.config creates=~/.config
  sudo: no

- name: Install powerline config
  copy: src=config/ dest=~/.config/powerline/
  sudo: no

- name: Install powerline
  pip: name='git+git://github.com/Lokaltog/powerline'
  sudo: yes

# vim: set ai et sw=2 syntax=yaml :
