---
- name: Create config folder
  command: mkdir ~/.config creates=~/.config
  sudo: no

- name: Remove old powerline config
  file: path=~/.config/powerline state=absent
  sudo: no

- name: Install powerline config
  copy: src=config/ dest=~/.config/powerline/
  sudo: no

- name: Remove old powerline
  file: path=/usr/local/src/powerline/ state=absent
  sudo: yes

- name: Install powerline
  copy: src=powerline/ dest=/usr/local/src/powerline/
  sudo: yes

- name: Make scripts executable
  file: path=/usr/local/src/powerline/scripts mode=0755 recurse=yes
  sudo: yes

- name: Build powerline
  command: python setup.py install chdir=/usr/local/src/powerline creates=/usr/local/bin/powerline-config
  sudo: yes

# vim: set ai et sw=2 syntax=yaml :
