---
- name: Create config folder
  command: mkdir ~/.config creates=~/.config
  sudo: no

- name: Install powerline config
  copy: src=config dest=~/.config/powerline
  sudo: no

- name: Install powerline
  copy: src=powerline dest=~/.powerline
  sudo: no
