---
- name: Create config folder
  command: mkdir ~/.config creates=~/.config
  sudo: no

- name: Remove old powerline config
  file: path=~/.config/powerline state=absent

- name: Install powerline config
  copy: src=config/ dest=~/.config/powerline/
  sudo: no

- name: Remove old powerline
  file: path=~/.powerline state=absent

- name: Install powerline
  copy: src=powerline/ dest=~/.powerline/
  sudo: no

- name: Make scripts executable
  file: path=~/.powerline/scripts mode=0755 recurse=yes
  sudo: no

- name: Build powerline
  command: python setup.py install --user chdir=~/.powerline/ creates=~/.local/bin/powerline-config
  sudo: no

# vim: set ai et sw=2 syntax=yaml :
