---
- name: Install libperl-dev
  apt: name=libperl-dev state=present
  sudo: yes
  when: can_sudo

- name: Install python-dev
  apt: name=python-dev state=present
  sudo: yes
  when: can_sudo

- name: Install libncurses5-dev
  apt: name=libncurses5-dev state=present
  sudo: yes
  when: can_sudo

- name: Install libncursesw5-dev
  apt: name=libncursesw5-dev state=present
  sudo: yes
  when: can_sudo

- name: Install make
  apt: name=make state=present
  sudo: yes
  when: can_sudo

- name: Install gcc
  apt: name=gcc state=present
  sudo: yes
  when: can_sudo

- name: Create bin folder
  command: mkdir -p ~/bin/source/vim creates=~/bin/source/vim
  sudo: no

# This isn't a submodule because this should always build the latest version
- name: Clone source code
  git: repo=https://github.com/b4winckler/vim.git dest=~/bin/source/vim version=master
  sudo: no

- name: Build vim
  script: build.sh creates=~/bin/vim
  sudo: no

# vim: set ai et sw=2 syntax=yaml :
