---
- name: Install fc-cache command
  apt: name=fontconfig state=present
  sudo: yes
  when: can_sudo

- name: Create fonts directory
  command: mkdir ~/.fonts creates=~/.fonts
  sudo: no
  when: can_sudo

- name: Install AnonymousPro font
  copy: src=powerline-fonts/AnonymousPro/ dest=~/.fonts/AnonymousPro/
  notify: Update system fonts cache
  sudo: no
  when: can_sudo

- name: Install DejaVuSansMono font
  copy: src=powerline-fonts/DejaVuSansMono/ dest=~/.fonts/DejaVuSansMono/
  notify: Update system fonts cache
  sudo: no
  when: can_sudo

- name: Install DroidSansMono font
  copy: src=powerline-fonts/DroidSansMono/ dest=~/.fonts/DroidSansMono/
  notify: Update system fonts cache
  sudo: no
  when: can_sudo

- name: Install Inconsolata-g font
  copy: src=powerline-fonts/Inconsolata/ dest=~/.fonts/Inconsolata/
  notify: Update system fonts cache
  sudo: no
  when: can_sudo

- name: Install Inconsolata font
  copy: src=powerline-fonts/Inconsolata/ dest=~/.fonts/Inconsolata/
  notify: Update system fonts cache
  sudo: no
  when: can_sudo

- name: Install InconsolataDz font
  copy: src=powerline-fonts/InconsolataDz/ dest=~/.fonts/InconsolataDz/
  notify: Update system fonts cache
  sudo: no
  when: can_sudo

- name: Install InputMono font
  copy: src=powerline-fonts/InputMono/ dest=~/.fonts/InputMono/
  notify: Update system fonts cache
  sudo: no
  when: can_sudo

- name: Install LiberationMono font
  copy: src=powerline-fonts/LiberationMono/ dest=~/.fonts/LiberationMono/
  notify: Update system fonts cache
  sudo: no
  when: can_sudo

- name: Install Meslo font
  copy: src=powerline-fonts/Meslo/ dest=~/.fonts/Meslo/
  notify: Update system fonts cache
  sudo: no
  when: can_sudo

- name: Install SourceCodePro font
  copy: src=powerline-fonts/SourceCodePro/ dest=~/.fonts/SourceCodePro/
  notify: Update system fonts cache
  sudo: no
  when: can_sudo

- name: Install Terminus font
  copy: src=powerline-fonts/Terminus/ dest=~/.fonts/Terminus/
  notify: Update system fonts cache
  sudo: no
  when: can_sudo

- name: Install UbuntuMono font
  copy: src=powerline-fonts/UbuntuMono/ dest=~/.fonts/UbuntuMono/
  notify: Update system fonts cache
  sudo: no
  when: can_sudo

# vim: set ai et sw=2 syntax=yaml :
